language: python

python:
  - "3.6"

cache:
  pip: true

install:
  - pip install -r requirements_dev.txt

script:
  - python manage.py test app --settings=django_example.settings.dev

branches:
  only:
    - master

deploy:
  provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always